
language: python
sudo: required

python:
  - "2.7"
  - "pypy"

addons:
  apt:
    packages:
       - libzmq3-dev
       - protobuf-compiler
       - libprotobuf-dev

services:
  - rabbitmq

before_script:
  - sudo rabbitmqctl add_user hydra hydra
  - sudo rabbitmqctl set_user_tags hydra administrator
  - sudo rabbitmqctl set_permissions hydra ".*" ".*" ".*"
  - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
  - mv zmq.hpp /home/travis/build/lake-lerna/hydra/src/main/c/zmq

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose

script:
  - pyb analyze
  - pyb publish -x run_unit_tests -x run_integration_tests -x verify
  - pyb install -x run_unit_tests -x run_integration_tests -x verify
  - pyb positive_test || false 
  - (!pyb negative_test) || false
  - pyb test --verbose

after_script:
  - cat /home/travis/build/lake-lerna/hydra/live/*.log
